// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN5Y9_0EWklXot1tvvMTgp9Mthb13cIRs',
    appId: '1:1092390748256:web:4f5626ab52222156120305',
    messagingSenderId: '1092390748256',
    projectId: 'my-video-game-archive',
    authDomain: 'my-video-game-archive.firebaseapp.com',
    databaseURL: 'https://my-video-game-archive-default-rtdb.firebaseio.com',
    storageBucket: 'my-video-game-archive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAk9YKncupskKJEXqN-R7LlGpCrZV_OAM',
    appId: '1:1092390748256:android:6e678f03df9f98ee120305',
    messagingSenderId: '1092390748256',
    projectId: 'my-video-game-archive',
    databaseURL: 'https://my-video-game-archive-default-rtdb.firebaseio.com',
    storageBucket: 'my-video-game-archive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARMZ3UdGwwfd36NAwzemvehTdgFrJcbT4',
    appId: '1:1092390748256:ios:b263432f3e7e7478120305',
    messagingSenderId: '1092390748256',
    projectId: 'my-video-game-archive',
    databaseURL: 'https://my-video-game-archive-default-rtdb.firebaseio.com',
    storageBucket: 'my-video-game-archive.appspot.com',
    androidClientId: '1092390748256-kpg2c1m08f3096ooev8tg8sm0evrnqio.apps.googleusercontent.com',
    iosClientId: '1092390748256-h6mg7995ldc7rlf8srg6oc8em3p3akc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVideoGameArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARMZ3UdGwwfd36NAwzemvehTdgFrJcbT4',
    appId: '1:1092390748256:ios:b263432f3e7e7478120305',
    messagingSenderId: '1092390748256',
    projectId: 'my-video-game-archive',
    databaseURL: 'https://my-video-game-archive-default-rtdb.firebaseio.com',
    storageBucket: 'my-video-game-archive.appspot.com',
    androidClientId: '1092390748256-kpg2c1m08f3096ooev8tg8sm0evrnqio.apps.googleusercontent.com',
    iosClientId: '1092390748256-h6mg7995ldc7rlf8srg6oc8em3p3akc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVideoGameArchive',
  );
}
